// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfflqO3qKnhDRqBWtOLosW_fouCm1DHBg',
    appId: '1:652342753223:web:202ab854b892b9358ecbe2',
    messagingSenderId: '652342753223',
    projectId: 'attendance-app-d29ad',
    authDomain: 'attendance-app-d29ad.firebaseapp.com',
    storageBucket: 'attendance-app-d29ad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_WNNGod_i5YIKIHEBiaHYG46QI2Ksxo4',
    appId: '1:652342753223:android:f613ab7e140296b48ecbe2',
    messagingSenderId: '652342753223',
    projectId: 'attendance-app-d29ad',
    storageBucket: 'attendance-app-d29ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ53MPMECcmQAV4LoJJesTFWIqPz7DV_A',
    appId: '1:652342753223:ios:9ef2bf802cd388ce8ecbe2',
    messagingSenderId: '652342753223',
    projectId: 'attendance-app-d29ad',
    storageBucket: 'attendance-app-d29ad.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ53MPMECcmQAV4LoJJesTFWIqPz7DV_A',
    appId: '1:652342753223:ios:9ef2bf802cd388ce8ecbe2',
    messagingSenderId: '652342753223',
    projectId: 'attendance-app-d29ad',
    storageBucket: 'attendance-app-d29ad.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfflqO3qKnhDRqBWtOLosW_fouCm1DHBg',
    appId: '1:652342753223:web:b8d43259fe9d943a8ecbe2',
    messagingSenderId: '652342753223',
    projectId: 'attendance-app-d29ad',
    authDomain: 'attendance-app-d29ad.firebaseapp.com',
    storageBucket: 'attendance-app-d29ad.firebasestorage.app',
  );
}